services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $youtube: '@contao_youtube_sync.google_service_youtube'
            $projectDir: '%kernel.project_dir%'
    
    InspiredMinds\ContaoYouTubeSync\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,Event,ContaoYouTubeSyncBundle.php}

    contao_youtube_sync.google_client:
        class: Google\Client
        arguments:
            -
              application_name: '%contao_youtube_sync.application_name%'
              developer_key: '%contao_youtube_sync.developer_key%'
    
    contao_youtube_sync.google_service_youtube:
        class: Google\Service\YouTube
        arguments:
            - '@contao_youtube_sync.google_client'
